from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
import os

def text_to_ppt(input_text, template_file="modules/your_template.pptx", output_file="output.pptx", theme="professional"):
    try:
        # Check if the template file exists
        if not os.path.exists(template_file):
            raise FileNotFoundError(f"Template file not found: {template_file}")

        # Check if the input text is empty
        if not input_text or not input_text.strip():
            raise ValueError("Input text is empty")

        # Create a presentation object
        prs = Presentation(template_file)

        # Define themes (colors and fonts)
        themes = {
            "professional": {"bg_color": RGBColor(255, 255, 255), "text_color": RGBColor(0, 0, 0), "font": "Calibri"},
            "creative": {"bg_color": RGBColor(173, 216, 230), "text_color": RGBColor(0, 0, 139), "font": "Comic Sans MS"},
            "minimalistic": {"bg_color": RGBColor(245, 245, 245), "text_color": RGBColor(64, 64, 64), "font": "Arial"},
        }

        # Apply theme
        bg_color = themes[theme]["bg_color"]
        text_color = themes[theme]["text_color"]
        font = themes[theme]["font"]

        # Add a title slide (only for the first slide)
        slide_layout = prs.slide_layouts[0]  # Title slide layout
        slide = prs.slides.add_slide(slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = "My Presentation"
        subtitle.text = "Generated by Python"
        title.text_frame.paragraphs[0].font.color.rgb = text_color
        subtitle.text_frame.paragraphs[0].font.color.rgb = text_color

        # Split the input text into sentences based on full stops
        sentences = [sentence.strip() for sentence in input_text.strip().split(".") if sentence]

        # Add each sentence to a new slide (without a title)
        for sentence in sentences:
            slide_layout = prs.slide_layouts[6]  # Blank layout (no title)
            slide = prs.slides.add_slide(slide_layout)

            # Add a text box for the content
            left = Inches(2.5)  # 1 inch from the left
            top = Inches(1)   # 1 inch from the top
            width = Inches(8)  # 8 inches wide
            height = Inches(5)  # 5 inches tall
            textbox = slide.shapes.add_textbox(left, top, width, height)
            text_frame = textbox.text_frame

            # Enable word wrap
            text_frame.word_wrap = True
            text_frame.vertical_anchor = MSO_ANCHOR.MIDDLE

            # Add the sentence to the text box
            p = text_frame.add_paragraph()
            p.text = sentence
            p.font.size = Pt(24)
            p.font.color.rgb = text_color
            p.font.name = font
            p.alignment = PP_ALIGN.LEFT  # Align left or adjust based on your preference

        # Save the presentation
        prs.save(output_file)
        print(f"Presentation saved as {output_file}")
        return True

    except Exception as e:
        print(f"Error generating PowerPoint: {e}")
        return False